CREATE TABLE IF NOT EXISTS ACCOUNT(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50),
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    CREATED_ON TIMESTAMP(3) WITH TIME ZONE NOT NULL,
    MODIFIED_ON TIMESTAMP(3) WITH TIME ZONE NOT NULL
);